[FIXUP]sched: Add API to migrate the current process to a given cpumask
• Due to the changes made in https://github.com/Atom-X-Devs/android_kernel_asus_sdm660/commit/8d60ad7c7f85103dadb4f7e0eab26264d414ab56,
     we were greeted by some very annoying warns after picking https://github.com/Atom-X-Devs/android_kernel_asus_sdm660/commit/1a2a4801548b2e00731b04b79e40d75f82cb57be

../kernel/sched/core.c:2145:46: error: no member named 'cpus_allowed' in 'struct task_struct'
        *cpumask_bits(old_mask) = *cpumask_bits(&p->cpus_allowed);
                                                 ~  ^
../include/linux/cpumask.h:25:31: note: expanded from macro 'cpumask_bits'
                              ^~~~~
../kernel/sched/core.c:2166:24: error: no member named 'cpus_allowed' in 'struct task_struct'
        if (*cpumask_bits(&p->cpus_allowed) == *cpumask_bits(dest)) {
                           ~  ^
../include/linux/cpumask.h:25:31: note: expanded from macro 'cpumask_bits'
                              ^~~~~
2 errors generated.
make[3]: *** [../scripts/Makefile.build:338: kernel/sched/core.o] Error 1
make[2]: *** [../scripts/Makefile.build:642: kernel/sched] Error 2
make[1]: *** Waiting for unfinished jobs....

Change-Id: I116f66b2b2bcfd2e4cbf553785aaa492134b777c
Signed-off-by: Kunmun <kunmun.devroms@gmail.com>