drivers: input: cdfinger: {X00TD, X01BD}: Drop cpu boost
• This invokes a build error now due to implicit function as we have dropped CPU_BOOST config

	../drivers/input/fingerprint/cdfinger_X01BD/cdfingerfp.c:179:9: error: implicit declaration of function 'sched_set_boost' [-Werror,-Wimplicit-function-declaration]
	                ret = sched_set_boost(0);
	                      ^
	../drivers/input/fingerprint/focaltech_X01BD/ff_ctl.c:148:9: error: implicit declaration of function 'sched_set_boost' [-Werror,-Wimplicit-function-declaration]
	                ret = sched_set_boost(0);
	                      ^
	../drivers/input/fingerprint/cdfinger_X01BD/cdfingerfp.c:192:9: error: implicit declaration of function 'sched_set_boost' [-Werror,-Wimplicit-function-declaration]
	                ret = sched_set_boost(1);
	                      ^
	../drivers/input/fingerprint/focaltech_X01BD/ff_ctl.c:161:9: error: implicit declaration of function 'sched_set_boost' [-Werror,-Wimplicit-function-declaration]
	                ret = sched_set_boost(1);
			      ^
	2 errors generated.

• Previously it used to complain in logs that it never worked as we arent HMP anymore.
• Also why the heck do we need cpu boost in a fp driver? Why Asus?

Change-Id: I87f5990be5d3db3fd0478f9bcbb558c4b5c450e9
Co-authored-by: Kunmun <kunmun.devroms@gmail.com>
Signed-off-by: Kunmun <kunmun.devroms@gmail.com>